class_name Constants

const TILE_SIZE: int = 16

const ROCKET_FORCE: float = -15.0
const ROCKET_MIN_FUEL: int = 5
const GRAVITY: int = 10


enum COLLISION_LAYERS {GROUND_WALLS_DEFAULT, DEAD_AREA, PLAYER, SHOOT_BLOCK, BOUNCE_BACK_BLOCK, UP_DOWN_LEFT_RIGHT_BLOCK}
